service: python-example-environment-variables
frameworkVersion: '2'
provider:
  name: aws
  runtime: python2.7
  lambdaHashingVersion: 20201221
  profile: serverless-admin
  region: eu-west-1
  environment:
    variable1: value1
    variable2: value2
    FIRST_NAME: John
functions:
  hello-env-john:
    handler: handler.hello
  hello-env-marc:
    handler: handler.hello
    environment:
      FIRST_NAME: Marc
