service: service-05-python-s3-thumbnail
frameworkVersion: '2'
provider:
  name: aws
  runtime: python2.7
  lambdaHashingVersion: 20201221
  region: eu-west-1
  profile: serverless-admin
  timeout: 10
  memorySize: 128
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "s3:*"
      Resource: "*"
  environment:
    THUMBNAIL_SIZE: 128

custom:
  bucket: davis-s3-thumbnail-generator
  pythonRequirements:
    dockerizePip: true

functions:
  s3-thumbnail-generator:
    handler: handler.s3_thumbnail_generator
    events:
      - s3:
          bucket: ${self:custom.bucket}
          event: s3:ObjectCreated:*
          rules:
            - suffix: .png
plugins:
  - serverless-python-requirements
