service: python-example-iam
frameworkVersion: '2'

provider:
  name: aws
  runtime: python2.7
  lambdaHashingVersion: 20201221
  profile: serverless-admin
  region: eu-west-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:*
      Resource:
        - "*"
functions:
  hello:
    handler: handler.hello
